# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b0d1dcdf6bec95fa2c70c4d5d6259017d26af45f37e68bf47e249854f469b5827cb06c197fe6d07f23706f655d1fd427fc46ad0e3c661664909694bc3b8235e

test:
  secret_key_base: 0a886413537c6db2340f4924efac5699dce48359d797bd4bfe90671a0553a587e360ddea2b6293d9f94133431fc2c24c29fa4c9c1c10cd06878647a15d13a143

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
